# Generated by Django 5.2.13 on 2026-04-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Production-Server-1', max_length=100)),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('ssh_user', models.CharField(default='ubuntu', max_length=50)),
                ('is_active', models.BooleanField(default=False, help_text='True if Ansible setup is complete')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
