# Generated by Django 5.2.13 on 2026-04-10 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_alter_server_options_server_cadvisor_port_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., High CPU Alert', max_length=150)),
                ('metric', models.CharField(choices=[('cpu_usage', 'CPU Usage (%)'), ('memory_usage', 'Memory Usage (%)'), ('disk_usage', 'Disk Usage (%)'), ('node_exporter_down', 'Node Exporter Down'), ('cadvisor_down', 'cAdvisor Down')], max_length=30)),
                ('threshold', models.FloatField(default=90.0, help_text="Threshold value. For CPU/Memory/Disk this is percentage. For 'down' alerts, set to 0.")),
                ('severity', models.CharField(choices=[('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=10)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['metric', 'severity'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('metric_name', models.CharField(max_length=50)),
                ('metric_value', models.FloatField(blank=True, null=True)),
                ('threshold_value', models.FloatField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('fixing', 'Fix In Progress'), ('fixed', 'Fixed'), ('failed', 'Fix Failed'), ('dismissed', 'Dismissed')], default='open', max_length=15)),
                ('fix_command', models.TextField(blank=True, default='', help_text='The SSH command that will be executed to fix this issue')),
                ('fix_description', models.CharField(blank=True, default='', help_text='Human-readable description of what the fix does', max_length=200)),
                ('fix_logs', models.TextField(blank=True, default='', help_text='Output from executing the fix command')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fixed_at', models.DateTimeField(blank=True, null=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='monitor.server')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='monitor.alertrule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
