# Generated by Django 4.2.30 on 2026-04-11 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_alter_server_options_server_cadvisor_port_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(help_text='e.g., cpu_usage, memory_usage, disk_usage', max_length=50)),
                ('severity', models.CharField(choices=[('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True, default='')),
                ('metric_value', models.FloatField(blank=True, help_text='The metric value that triggered the alert', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('auto_fixed', 'Auto-Fixed')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='server',
            name='auto_fix_enabled',
            field=models.BooleanField(default=False, help_text='If True, self-healing actions will execute automatically on critical alerts'),
        ),
        migrations.CreateModel(
            name='FixExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=50)),
                ('commands_run', models.TextField(blank=True, default='[]', help_text='JSON array of command result objects')),
                ('summary', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], default='failed', max_length=20)),
                ('triggered_by', models.CharField(default='manual', help_text="'manual' or 'auto'", max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fix_executions', to='monitor.alert')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fix_executions', to='monitor.server')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='alert',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='monitor.server'),
        ),
    ]
