# Generated by Django 4.2.30 on 2026-04-11 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_alert_server_auto_fix_enabled_fixexecution_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_graphs', models.JSONField(blank=True, default=list)),
                ('is_customized', models.BooleanField(default=False)),
                ('server', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_config', to='monitor.server')),
            ],
        ),
    ]
